/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/h78nVVfZnbV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function landing() {
  return (<>
    <header
      className="flex items-center justify-between px-4 py-3 bg-[#5599ff] text-white shadow-md">
      <div className="flex items-center space-x-2">
        <img
          alt="AdaptED Logo"
          height={40}
          src="/placeholder.svg"
          style={{
            aspectRatio: "40/40",
            objectFit: "cover",
          }}
          width={40} />
        <span className="text-xl font-bold">AdaptED</span>
      </div>
      <nav className="hidden md:flex space-x-4">
        <Link className="flex items-center space-x-2 hover:text-gray-200" href="#">
          <HomeIcon className="h-5 w-5" />
          <span>Home</span>
        </Link>
        <Link className="flex items-center space-x-2 hover:text-gray-200" href="#">
          <BookIcon className="h-5 w-5" />
          <span>Learn</span>
        </Link>
        <Link className="flex items-center space-x-2 hover:text-gray-200" href="#">
          <GamepadIcon className="h-5 w-5" />
          <span>Play</span>
        </Link>
        <Link className="flex items-center space-x-2 hover:text-gray-200" href="#">
          <InfoIcon className="h-5 w-5" />
          <span>About</span>
        </Link>
      </nav>
      <button className="md:hidden">
        <MenuIcon className="h-6 w-6" />
      </button>
    </header>
    <main>
      <section
        className="bg-[#5599ff] text-white py-20 px-4 md:px-8 flex flex-col items-center md:flex-row justify-between">
        <div className="space-y-4 max-w-md">
          <h1 className="text-4xl font-bold">Welcome to AdaptED</h1>
          <p className="text-lg">Unlock your child's potential with our engaging educational platform.</p>
          <div className="flex space-x-4">
            <Button variant="primary">Start Learning!</Button>
            <Button variant="secondary">Play Games!</Button>
          </div>
        </div>
        <div className="mt-8 md:mt-0">
          <img
            alt="Owl Mascot"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/300",
              objectFit: "cover",
            }}
            width={300} />
        </div>
      </section>
      <section className="py-20 px-4 md:px-8 flex flex-col items-center">
        <div className="space-y-4 max-w-md text-center">
          <h2 className="text-3xl font-bold">Explore and Learn</h2>
          <p className="text-gray-600">Discover our interactive educational games and videos.</p>
        </div>
        <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-[#F5F5F5] rounded-lg p-6 flex flex-col items-center">
            <img
              alt="Game Icon"
              height={100}
              src="/placeholder.svg"
              style={{
                aspectRatio: "100/100",
                objectFit: "cover",
              }}
              width={100} />
            <h3 className="text-2xl font-bold mt-4">Educational Games</h3>
            <p className="text-gray-600 mt-2">
              Engage your child with fun and challenging games that teach valuable skills.
            </p>
            <Button className="mt-4" variant="link">
              Play Now
            </Button>
          </div>
          <div className="bg-[#F5F5F5] rounded-lg p-6 flex flex-col items-center">
            <img
              alt="Video Icon"
              height={100}
              src="/placeholder.svg"
              style={{
                aspectRatio: "100/100",
                objectFit: "cover",
              }}
              width={100} />
            <h3 className="text-2xl font-bold mt-4">Instructional Videos</h3>
            <p className="text-gray-600 mt-2">
              Explore our collection of educational videos to enhance your child's learning.
            </p>
            <Button className="mt-4" variant="link">
              Watch Now
            </Button>
          </div>
        </div>
      </section>
      <section className="bg-[#F5F5F5] py-20 px-4 md:px-8">
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold">About AdaptED</h2>
            <p className="text-gray-600">
              AdaptED is an innovative educational platform designed to help children learn and grow. Our mission is
              to make learning fun and engaging, while also improving key skills like math, reading, and
              problem-solving.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white rounded-lg p-4 flex items-center space-x-4">
                <div className="bg-[#5599ff] rounded-full p-2 text-white">
                  <CalculatorIcon className="h-6 w-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold">Math Skills</h3>
                  <p className="text-gray-600 text-sm">
                    Improve your child's math proficiency with our engaging exercises.
                  </p>
                </div>
              </div>
              <div className="bg-white rounded-lg p-4 flex items-center space-x-4">
                <div className="bg-[#5599ff] rounded-full p-2 text-white">
                  <BookIcon className="h-6 w-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold">Reading Comprehension</h3>
                  <p className="text-gray-600 text-sm">
                    Encourage your child's love of reading with our interactive stories.
                  </p>
                </div>
              </div>
              <div className="bg-white rounded-lg p-4 flex items-center space-x-4">
                <div className="bg-[#5599ff] rounded-full p-2 text-white">
                  <PuzzleIcon className="h-6 w-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold">Problem-Solving</h3>
                  <p className="text-gray-600 text-sm">
                    Develop critical thinking skills with our challenging puzzles and games.
                  </p>
                </div>
              </div>
              <div className="bg-white rounded-lg p-4 flex items-center space-x-4">
                <div className="bg-[#5599ff] rounded-full p-2 text-white">
                  <RocketIcon className="h-6 w-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold">Personalized Learning</h3>
                  <p className="text-gray-600 text-sm">
                    Our platform adapts to each child's unique needs and learning style.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex items-center justify-center">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden">
              <span className="w-full h-auto rounded-md bg-gray-100 dark:bg-gray-800" />
            </div>
          </div>
        </div>
      </section>
    </main>
    <footer className="bg-[#5599ff] text-white py-8 px-4 md:px-8">
      <div
        className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between items-center">
        <div className="flex items-center space-x-2">
          <img
            alt="AdaptED Logo"
            height={40}
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width={40} />
          <span className="text-xl font-bold">AdaptED</span>
        </div>
        <nav className="flex space-x-4 mt-4 md:mt-0">
          <Link className="hover:text-gray-200" href="#">
            Home
          </Link>
          <Link className="hover:text-gray-200" href="#">
            Learn
          </Link>
          <Link className="hover:text-gray-200" href="#">
            Play
          </Link>
          <Link className="hover:text-gray-200" href="#">
            About
          </Link>
        </nav>
        <div className="flex space-x-4 mt-4 md:mt-0">
          <Link className="hover:text-gray-200" href="#">
            <FacebookIcon className="h-6 w-6" />
          </Link>
          <Link className="hover:text-gray-200" href="#">
            <TwitterIcon className="h-6 w-6" />
          </Link>
          <Link className="hover:text-gray-200" href="#">
            <InstagramIcon className="h-6 w-6" />
          </Link>
        </div>
      </div>
    </footer>
  </>);
}

function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function CalculatorIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="16" height="20" x="4" y="2" rx="2" />
      <line x1="8" x2="16" y1="6" y2="6" />
      <line x1="16" x2="16" y1="14" y2="18" />
      <path d="M16 10h.01" />
      <path d="M12 10h.01" />
      <path d="M8 10h.01" />
      <path d="M12 14h.01" />
      <path d="M8 14h.01" />
      <path d="M12 18h.01" />
      <path d="M8 18h.01" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function GamepadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function InfoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PuzzleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>)
  );
}


function RocketIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path
        d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}
